#!/bin/bash

source "$HOME/.config/theme/borders.sh"

options=(
  style=rounded
  width=4.0
  hidpi=on
  active_color="${BORDERS_ACTIVE_COLOR:-0xffebbcba}"
  inactive_color="${BORDERS_INACTIVE_COLOR:-0xff6e6a86}"
)

borders "${options[@]}"
