[".config/zellij/plugins/zjstatus.wasm"]
type = "file"
url = "https://github.com/dj95/zjstatus/releases/download/v0.22.0/zjstatus.wasm"
refreshPeriod = "168h"

[".config/zellij/plugins/vim-zellij-navigator.wasm"]
type = "file"
url = "https://github.com/hiasr/vim-zellij-navigator/releases/download/0.3.0/vim-zellij-navigator.wasm"
refreshPeriod = "168h"

[".local/share/blesh"]
type = "archive"
url = "https://github.com/akinomyoga/ble.sh/releases/download/v0.3.4/ble-0.3.4.tar.xz"
stripComponents = 1
refreshPeriod = "168h"

[".config/tmux/plugins/tpm"]


{{ if eq .chezmoi.os "linux" }}
type = "archive"
url = "https://github.com/tmux-plugins/tpm/archive/refs/heads/master.zip"
stripComponents = 1
refreshPeriod = "168h"
[".local/share/fonts/GeistMonoNerdFont"]

{{ end }}
type = "archive"
url = "https://github.com/ryanoasis/nerd-fonts/releases/download/v3.4.0/GeistMono.zip"
checksum.sha256 = "a9f61b7b7f0429db4fa9a526940f71190127ed95dbe3533163d80d7cafdb3ec9"
include = ["*.otf"]
exact = true
