[".config/zellij/plugins/zjstatus.wasm"]
type = "file"
url = "https://github.com/dj95/zjstatus/releases/download/v0.22.0/zjstatus.wasm"
refreshPeriod = "168h"

[".config/zellij/plugins/vim-zellij-navigator.wasm"]
type = "file"
url = "https://github.com/hiasr/vim-zellij-navigator/releases/download/0.3.0/vim-zellij-navigator.wasm"
refreshPeriod = "168h"

[".local/share/blesh"]
type = "archive"
url = "https://github.com/akinomyoga/ble.sh/releases/download/v0.3.4/ble-0.3.4.tar.xz"
stripComponents = 1
refreshPeriod = "168h"

[".config/tmux/plugins/tpm"]
type = "archive"
url = "https://github.com/tmux-plugins/tpm/archive/refs/heads/master.zip"
stripComponents = 1
refreshPeriod = "168h"

[".config/herdr/plugins/vim-herdr-navigation"]
type = "archive"
url = "https://github.com/paulbkim-dev/vim-herdr-navigation/archive/53e318c772c4d3b7fbd904ac43bcf3e5b5d8b244.zip"
stripComponents = 1
refreshPeriod = "168h"
