[settings]
aqua.github_attestations = false

[tools]
7zip = "latest"
actionlint = "latest"
ast-grep = "latest"
awscli = "latest"
bat = "latest"
btop = "latest"
bun = "latest"
chezmoi = "latest"
difftastic = "latest"
fd = "latest"
ffmpeg = "latest"
fzf = "latest"
gh = "latest"
git-lfs = "latest"
go = "latest"
"go:github.com/go-delve/delve/cmd/dlv" = "latest"
"go:golang.org/x/tools/cmd/goimports" = "latest"
"go:mvdan.cc/gofumpt" = "latest"
gradle = "latest"
helm = "latest"
herdr = "latest"
imagemagick = "latest"
java = ["latest", "corretto-21"]
jj = "latest"
jq = "latest"
k9s = "latest"
kubectl = "latest"
lazydocker = "latest"
lazygit = "latest"
lsd = "latest"
lua = "latest"
markdownlint-cli2 = "latest"
neovim = "latest"
node = "latest"
pnpm = "latest"
python = ["latest", "3.13"]
resvg = "latest"
ripgrep = "latest"
ruby = "latest"
ruff = "latest"
rust = "stable"
sccache = "latest"
semgrep = "latest"
shellcheck = "latest"
sqlite = "latest"
starship = "latest"
stylua = "latest"
syncthing = "latest"
taplo = "latest"
terraform = "latest"
tmux = "latest"
tree-sitter = "latest"
uv = "latest"
yazi = "latest"
yq = "latest"
zellij = "latest"
zig = "latest"
zoxide = "latest"
