local hyper = { "ctrl", "alt", "cmd" }
local hotkeyDocs = {}
local log = hs.logger.new("init", "info")

-- Watchers, timers, and menubar items held only by locals can be garbage
-- collected once init.lua finishes, which silently stops them. Keep them here.
keepAlive = {}

local function notify(message)
  hs.alert.show(message, 1.2)
end

local function bind(mods, key, description, fn)
  table.insert(hotkeyDocs, {
    combo = table.concat(mods, "+") .. "+" .. key,
    description = description,
  })
  hs.hotkey.bind(mods, key, fn)
end

local function showCheatsheet()
  table.sort(hotkeyDocs, function(a, b)
    return a.combo < b.combo
  end)

  local lines = { "Hammerspoon shortcuts" }
  for _, item in ipairs(hotkeyDocs) do
    table.insert(lines, string.format("%s  -  %s", item.combo, item.description))
  end
  hs.alert.show(table.concat(lines, "\n"), 4)
end

local function reloadConfig(files)
  for _, file in ipairs(files) do
    if file:sub(-4) == ".lua" then
      hs.reload()
      return
    end
  end
end

keepAlive.reloader = hs.pathwatcher.new(hs.configdir, reloadConfig):start()

local home = os.getenv("HOME")
local appDirs = {
  "/Applications",
  "/Applications/Utilities",
  "/System/Applications",
  "/System/Applications/Utilities",
  "/System/Library/CoreServices/Finder.app",
  home .. "/Applications",
}

local function collectApps(path, seen, apps)
  if path:sub(-4) == ".app" then
    local name = path:match("([^/]+)%.app$")
    if not seen[name] then
      seen[name] = true
      table.insert(apps, { text = name, subText = path, path = path })
    end
    return
  end

  if hs.fs.attributes(path, "mode") ~= "directory" then
    return
  end
  for entry in hs.fs.dir(path) do
    if entry:sub(-4) == ".app" then
      collectApps(path .. "/" .. entry, seen, apps)
    end
  end
end

-- Scans on every open so newly installed apps appear without a reload.
local function installedApps()
  local seen, apps = {}, {}
  for _, dir in ipairs(appDirs) do
    collectApps(dir, seen, apps)
  end
  table.sort(apps, function(a, b)
    return a.text:lower() < b.text:lower()
  end)
  for _, app in ipairs(apps) do
    app.image = hs.image.iconForFile(app.path)
  end
  return apps
end

local appChooser = hs.chooser.new(function(choice)
  if not choice then
    return
  end
  hs.application.launchOrFocus(choice.path)
end)
appChooser:placeholderText("Launch or focus an app")

local function showAppChooser()
  appChooser:choices(installedApps())
  appChooser:show()
end

local clipboardHistory = {}
local maxClipboardItems = 30
local lastChangeCount = hs.pasteboard.changeCount()

local function pushClipboard(text)
  if text == "" then
    return
  end

  if clipboardHistory[1] == text then
    return
  end

  for i = #clipboardHistory, 1, -1 do
    if clipboardHistory[i] == text then
      table.remove(clipboardHistory, i)
      break
    end
  end

  table.insert(clipboardHistory, 1, text)
  if #clipboardHistory > maxClipboardItems then
    table.remove(clipboardHistory)
  end
end

-- Password managers (1Password included) tag secrets with these pasteboard
-- types so clipboard history tools skip them. See http://nspasteboard.org.
local skippedPasteboardTypes = {
  ["org.nspasteboard.ConcealedType"] = true,
  ["org.nspasteboard.TransientType"] = true,
  ["org.nspasteboard.AutoGeneratedType"] = true,
  ["com.agilebits.onepassword"] = true,
}

local function isSensitiveClipboard()
  for _, contentType in ipairs(hs.pasteboard.contentTypes() or {}) do
    if skippedPasteboardTypes[contentType] then
      return true
    end
  end
  return false
end

keepAlive.clipboardTimer = hs.timer.doEvery(0.8, function()
  local currentChangeCount = hs.pasteboard.changeCount()
  if currentChangeCount == lastChangeCount then
    return
  end

  lastChangeCount = currentChangeCount
  if isSensitiveClipboard() then
    return
  end

  local text = hs.pasteboard.getContents()
  if text then
    pushClipboard(text)
  end
end)

local clipboardChooser = hs.chooser.new(function(choice)
  if not choice then
    return
  end
  hs.pasteboard.setContents(choice.text)
  notify("Copied from history")
end)
clipboardChooser:placeholderText("Clipboard history")

local function showClipboardChooser()
  local choices = {}
  for _, value in ipairs(clipboardHistory) do
    local compact = value:gsub("\n", " ")
    table.insert(choices, {
      text = value,
      subText = compact:sub(1, 120),
    })
  end

  clipboardChooser:choices(choices)
  clipboardChooser:show()
end

-- Caffeine modes:
--   "auto" - on while on AC power, off on battery
--   "on"   - manually pinned on, ignores power changes
--   "off"  - manually pinned off, ignores power changes
-- The mode persists across config reloads.
local caffeineModeKey = "caffeine.mode"
local caffeineModeOrder = { auto = "on", on = "off", off = "auto" }
local caffeineMode = hs.settings.get(caffeineModeKey)
if not caffeineModeOrder[caffeineMode] then
  caffeineMode = "auto"
end
hs.settings.clear("caffeine.manualOverride") -- superseded by caffeine.mode

local function caffeineWanted()
  if caffeineMode == "auto" then
    return hs.battery.powerSource() == "AC Power"
  end
  return caffeineMode == "on"
end

local function caffeineLabel(enabled)
  local mode = caffeineMode == "auto" and "auto" or "manual"
  return string.format("Caffeine: %s (%s)", enabled and "ON" or "OFF", mode)
end

-- Menubar icon: a filled, steaming cup while caffeine is on and an empty cup
-- while sleep is allowed; a small "A" marks auto mode. Template images follow
-- the menubar's light/dark appearance. Clicking cycles the mode like Hyper+C.
local function drawCaffeineIcon(enabled, auto)
  local scale = 2 -- draw at 2x so the icon stays sharp on Retina displays
  local width = auto and 26 or 17
  local black = { red = 0, green = 0, blue = 0, alpha = 1 }

  local function pt(x, y)
    return { x = x * scale, y = y * scale }
  end

  local function curve(x1, y1, c1x, c1y, c2x, c2y, x2, y2)
    local finish = pt(x2, y2)
    finish.c1x, finish.c1y = c1x * scale, c1y * scale
    finish.c2x, finish.c2y = c2x * scale, c2y * scale
    return {
      type = "segments",
      action = "stroke",
      closed = false,
      strokeColor = black,
      strokeWidth = 1.4 * scale,
      strokeCapStyle = "round",
      coordinates = { pt(x1, y1), finish },
    }
  end

  local elements = {
    curve(12.8, 8.6, 16.6, 8.0, 16.6, 13.6, 12.8, 13.0), -- handle
    {
      type = "rectangle",
      action = enabled and "fill" or "stroke",
      frame = { x = 3 * scale, y = 7.5 * scale, w = 10 * scale, h = 8.5 * scale },
      roundedRectRadii = { xRadius = 2.2 * scale, yRadius = 2.2 * scale },
      fillColor = black,
      strokeColor = black,
      strokeWidth = 1.5 * scale,
    },
  }

  if enabled then
    table.insert(elements, curve(6, 6, 4.6, 4.6, 7.4, 3, 6, 1.5)) -- steam
    table.insert(elements, curve(9.8, 6, 8.4, 4.6, 11.2, 3, 9.8, 1.5))
  end

  if auto then
    table.insert(elements, {
      type = "text",
      text = "A",
      textFont = "Helvetica-Bold",
      textSize = 8.5 * scale,
      textColor = black,
      frame = { x = 18 * scale, y = 7.5 * scale, w = 8 * scale, h = 11 * scale },
    })
  end

  local canvas = hs.canvas.new({ x = 0, y = 0, w = width * scale, h = 18 * scale })
  canvas:appendElements(elements)
  local image = canvas:imageFromCanvas()
  canvas:delete()
  return image:size({ w = width, h = 18 }, true)
end

local caffeineIcons = {}
for _, enabled in ipairs({ true, false }) do
  for _, auto in ipairs({ true, false }) do
    caffeineIcons[tostring(enabled) .. tostring(auto)] = drawCaffeineIcon(enabled, auto)
  end
end

keepAlive.caffeineMenu = hs.menubar.new()

local function updateCaffeineMenu(enabled)
  local menu = keepAlive.caffeineMenu
  if not menu then
    return
  end
  menu:setIcon(caffeineIcons[tostring(enabled) .. tostring(caffeineMode == "auto")], true)
  menu:setTooltip(caffeineLabel(enabled) .. " - click to cycle auto / on / off")
end

-- Applies the current mode. Notifies when forced or when the state changes.
local function applyCaffeine(showNotification, force)
  local enabled = caffeineWanted()
  local changed = hs.caffeinate.get("displayIdle") ~= enabled
  if changed then
    hs.caffeinate.set("displayIdle", enabled)
  end
  updateCaffeineMenu(enabled)
  if showNotification and (changed or force) then
    notify(caffeineLabel(enabled))
  end
end

-- Cycles auto -> on (manual) -> off (manual) -> auto.
local function cycleCaffeine()
  caffeineMode = caffeineModeOrder[caffeineMode]
  hs.settings.set(caffeineModeKey, caffeineMode)
  applyCaffeine(true, true)
end

if keepAlive.caffeineMenu then
  keepAlive.caffeineMenu:setClickCallback(cycleCaffeine)
end

local lastPowerSource = nil

local function syncCaffeineWithPower(showNotification)
  local source = hs.battery.powerSource()
  -- The battery watcher fires on every battery change (e.g. percentage);
  -- only react when the power source actually changes.
  if source == lastPowerSource then
    return
  end
  lastPowerSource = source
  applyCaffeine(showNotification, false)
end

local function toggleMicMute()
  local input = hs.audiodevice.defaultInputDevice()
  if not input then
    notify("No input device found")
    return
  end

  local muted = input:inputMuted()
  input:setInputMuted(not muted)
  notify(not muted and "Mic: Muted" or "Mic: Live")
end

local function toggleDarkMode()
  local ok, _, result = hs.osascript.applescript([[
    tell application "System Events"
      tell appearance preferences
        set dark mode to not dark mode
        return dark mode
      end tell
    end tell
  ]])

  if not ok then
    notify("Dark mode toggle failed")
    return
  end

  notify(result and "Appearance: Dark" or "Appearance: Light")
end

local dotfilesDir = home .. "/.local/share/chezmoi"

local function openDotfiles()
  hs.task.new("/usr/bin/open", nil, { dotfilesDir }):start()
end

bind(hyper, "R", "Reload config", hs.reload)
bind(hyper, "A", "App launcher", showAppChooser)
bind(hyper, "V", "Clipboard history", showClipboardChooser)
bind(hyper, "C", "Cycle caffeine: auto / on / off", cycleCaffeine)
bind(hyper, "M", "Toggle microphone mute", toggleMicMute)
bind(hyper, "D", "Toggle dark mode", toggleDarkMode)
bind(hyper, "/", "Show shortcut cheatsheet", showCheatsheet)
bind(hyper, ".", "Toggle Hammerspoon console", hs.toggleConsole)
bind(hyper, "O", "Open dotfiles folder", openDotfiles)

keepAlive.powerWatcher = hs.battery.watcher
  .new(function()
    syncCaffeineWithPower(true)
  end)
  :start()
syncCaffeineWithPower(false)

log.i("config loaded")
notify("Hammerspoon ready")
